name: BeaconBreaker
version: '${project.version}'
main: de.aurum.beaconbraker.main.BeaconBreaker
api-version: '1.20'
commands:
  setlobbyspawn:
    description: Set the spawn for the lobby
    usage: /setlobbyspawn
  setteamposition:
    description: Set any position of any team
    usage: /setteamposition [Team] [Position]
  setchest:
    description: Set Spawn of Loot Chests
    usage: /setchest [ChestNumber]
  bbreload:
    description: Reload the plugin
    usage: /bbreload
