# ____                                    ____                     _
#|  _ \                                  |  _ \                   | |
#| |_) |  ___   __ _   ___  ___   _ __   | |_) | _ __  ___   __ _ | | __ ___  _ __
#|  _ <  / _ \ / _` | / __|/ _ \ | '_ \  |  _ < | '__|/ _ \ / _` || |/ // _ \| '__|
#| |_) ||  __/| (_| || (__| (_) || | | | | |_) || |  |  __/| (_| ||   <|  __/| |
#|____/  \___| \__,_| \___|\___/ |_| |_| |____/ |_|   \___| \__,_||_|\_\\___||_|
# _              _                            ___
#| |__  _  _    /_\  _  _  _ _  _  _  _ __  / __| __ _  _ __   ___  _ _
#| '_ \| || |  / _ \| || || '_|| || || '  \| (_ |/ _` || '  \ / -_)| '_|
#|_.__/ \_, | /_/ \_\\_,_||_|   \_,_||_|_|_|\___|\__,_||_|_|_|\___||_|
#       |__/


chat:
  prefix: '&6[&bBeaconBreaker&6] §b'
  joinMessage: '%Prefix% &6%Player% &ehat den server betreten'
  noPerm: '%Prefix% §cKeine Permission!'
  wrongSender: '%Prefix% §cDieser Command darf nur von Spielern ausgeführt werden'
  usage: '%Prefix% §c%Usage% '

game:
  teams:
    red:
      name: 'Rot'
      color: 'RED' #Colors need to be written out in caps. Possible values: AQUA, BLACK, BLUE, BOLD, DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_PURPLE, DARK_RED, GOLD, GRAY, GREEN, ITALIC, LIGHT_PURPLE, MAGIC, RED, RESET, STRIKETHROUGH, UNDERLINE, WHITE, YELLOW
      spawnpoint:
    blue:
      name: 'Blau'
      color: 'BLUE'
      spawnpoint: